### ISSUE TITLE
Подключить пакет в модулях hawk

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.types#2]
1. подключаем пакет сабмодулем в корне монорепы для удобства разработки

2. в модулях подключаем пакет ярном через гитхаб

> `yarn add <git remote url>#<branch/commit/tag>` installs a package from a remote git repository at specific git branch, git commit or git tag.

- api
- workers
- garage (?)

**Comment by nikmel2803** [comment]
done
